// Country (gl) and language (hl) option lists for the SEO Tools dropdowns.
// Codes are the Google gl/hl values; labels are shown in the UI.

export const COUNTRIES: { code: string; label: string }[] = [
  { code: "us", label: "United States" },
  { code: "gb", label: "United Kingdom" },
  { code: "gr", label: "Greece" },
  { code: "ru", label: "Russia" },
  { code: "ua", label: "Ukraine" },
  { code: "de", label: "Germany" },
  { code: "fr", label: "France" },
  { code: "es", label: "Spain" },
  { code: "it", label: "Italy" },
  { code: "pt", label: "Portugal" },
  { code: "nl", label: "Netherlands" },
  { code: "pl", label: "Poland" },
  { code: "tr", label: "Turkey" },
  { code: "cy", label: "Cyprus" },
  { code: "bg", label: "Bulgaria" },
  { code: "ro", label: "Romania" },
  { code: "cz", label: "Czechia" },
  { code: "at", label: "Austria" },
  { code: "ch", label: "Switzerland" },
  { code: "be", label: "Belgium" },
  { code: "se", label: "Sweden" },
  { code: "no", label: "Norway" },
  { code: "fi", label: "Finland" },
  { code: "dk", label: "Denmark" },
  { code: "ie", label: "Ireland" },
  { code: "ca", label: "Canada" },
  { code: "au", label: "Australia" },
  { code: "ae", label: "United Arab Emirates" },
  { code: "in", label: "India" },
  { code: "br", label: "Brazil" },
  { code: "mx", label: "Mexico" },
  { code: "ge", label: "Georgia" },
  { code: "kz", label: "Kazakhstan" },
];

export const LANGUAGES: { code: string; label: string }[] = [
  { code: "en", label: "English" },
  { code: "ru", label: "Russian" },
  { code: "uk", label: "Ukrainian" },
  { code: "el", label: "Greek" },
  { code: "de", label: "German" },
  { code: "fr", label: "French" },
  { code: "es", label: "Spanish" },
  { code: "it", label: "Italian" },
  { code: "pt", label: "Portuguese" },
  { code: "nl", label: "Dutch" },
  { code: "pl", label: "Polish" },
  { code: "tr", label: "Turkish" },
  { code: "ar", label: "Arabic" },
  { code: "hi", label: "Hindi" },
  { code: "zh", label: "Chinese" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "bg", label: "Bulgarian" },
  { code: "ro", label: "Romanian" },
  { code: "cs", label: "Czech" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovenian" },
  { code: "hr", label: "Croatian" },
  { code: "sr", label: "Serbian" },
  { code: "hu", label: "Hungarian" },
  { code: "sv", label: "Swedish" },
  { code: "fi", label: "Finnish" },
  { code: "da", label: "Danish" },
  { code: "no", label: "Norwegian" },
  { code: "et", label: "Estonian" },
  { code: "lv", label: "Latvian" },
  { code: "lt", label: "Lithuanian" },
  { code: "ka", label: "Georgian" },
  { code: "kk", label: "Kazakh" },
  { code: "az", label: "Azerbaijani" },
  { code: "hy", label: "Armenian" },
  { code: "he", label: "Hebrew" },
  { code: "fa", label: "Persian" },
  { code: "th", label: "Thai" },
  { code: "vi", label: "Vietnamese" },
  { code: "id", label: "Indonesian" },
  { code: "ms", label: "Malay" },
  { code: "tl", label: "Filipino" },
  { code: "sq", label: "Albanian" },
  { code: "mk", label: "Macedonian" },
  { code: "be", label: "Belarusian" },
  { code: "is", label: "Icelandic" },
  { code: "ga", label: "Irish" },
  { code: "cy", label: "Welsh" },
  { code: "af", label: "Afrikaans" },
  { code: "sw", label: "Swahili" },
];
